vm:
  hosts:
    os-builder:
      ansible_port: 22
      ansible_host: "{{ vm_ip }}"
      ansible_user: ubuntu
master:
  hosts:
    master:
      ansible_port: "{{ image_ssh_port }}"
      ansible_host: "{{ vm_ip }}"
      ansible_user: "{{ cluster_user }}"
      rpi_static_ip: "{{ master_static_ip }}"
node:
  hosts:
    node1:
      ansible_port: "{{ image_ssh_port }}"
      ansible_host: "{{ vm_ip }}"
      ansible_user: "{{ cluster_user }}"
      rpi_static_ip: 10.0.0.11
cluster:
  children:
    master:
    node:
