vm:
  hosts:
    os-builder:
      ansible_port: 22
      ansible_host: "{{ vm_ip }}"
      ansible_user: ubuntu
master:
  hosts:
    master1:
      rpi_static_ip: 10.0.90.10
      common_name: appliance-rpi.a53ed2d2.vpn.mekomsolutions.net
      ansible_port: 5555
      load_balancer_addresses:
        - 10.0.90.20-10.0.90.99

node:
  hosts:
    node1:
      rpi_static_ip: 10.0.90.11
      common_name: appliance-rpi.0d615a90.vpn.mekomsolutions.net
      ansible_port: 5551
    node2:
      rpi_static_ip: 10.0.90.12
      common_name: appliance-rpi.1facb382.vpn.mekomsolutions.net
      ansible_port: 5552

cluster:
  children:
    master:
    node:
