vm:
  hosts:
    os-builder:
      ansible_port: 22
      ansible_host: 10.182.31.179
      ansible_user: ubuntu
master:
  hosts:
    ubuntu:
      ansible_port: 5555
      ansible_host: 10.182.31.179
      ansible_user: rpi_admin
      rpi_static_ip: 10.0.0.10
node:

cluster:
  children:
    master:
    node:
