vm:
  hosts:
    os-builder:
      ansible_port: 22
      ansible_host: "{{ vm_ip }}"
      ansible_user: ubuntu
master:
  hosts:
    master1:
node:
  hosts:
    node1:
      rpi_static_ip: 10.0.0.11
    node2:
      rpi_static_ip: 10.0.0.12
cluster:
  children:
    master:
    node:
