---

- name: Install network tools
  apt:
    name: net-tools
    state: present

- name: Add hostname to hosts
  lineinfile:
    path: "{{ image_mount_point }}/etc/hosts"
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 {{ ansible_hostname }}"
