---

- name: Copy nfs manifest files
  template:
    src: "{{ item }}"
    dest: /opt/nfs/
  with_fileglob:
    - "manifests/*"

- name: Apply NFS manifests
  shell: "k3s kubectl apply -n appliance -f /opt/nfs"

- name: Wait for NFS pod to be 'Ready'
  shell: k3s kubectl wait pods -n appliance -l app=nfs-provisioner --for condition=Ready --timeout=1800s
