---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: logging-storage
  namespace: "rsyslog"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-pv
  namespace: "rsyslog"
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: logging-storage
  local:
    path: "{{ cluster_disk_mount_point }}/logging"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-pvc
  namespace: "rsyslog"
  labels:
    app: logging
spec:
  storageClassName: logging-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi