apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-deployment
  namespace: rsyslog
  labels:
    app: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      nodeSelector:
        role: database
      containers:
      - name: rsyslog
        image: enyachoke/rsyslog:latest
        ports:
        - name: tcp
          containerPort: 514
          protocol: TCP
        - name: udp
          containerPort: 514
          protocol: UDP        
        volumeMounts:
          - name: logs
            mountPath: "/var/log"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logging-pvc