apiVersion: v1
kind: Service
metadata:
  name: "rsyslog"
  namespace: "rsyslog"
spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
      name: tcp
    - port: 514
      targetPort: 514
      protocol: UDP
      name: udp
  type: ClusterIP
  selector:
    app: "rsyslog"