apiVersion: v1
kind: Service
metadata:
  name: "rsyslo-ingress-svc"
  namespace: "rsyslog"
spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "rsyslog"
