---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  with_items:
    - "127.0.0.1 {{ inventory_hostname }}"

- name: Ensure K3s master service is disabled
  systemd:
    name: k3s
    daemon_reload: yes
    enabled: no
  when: not master_service

- name: Ensure K3s master service is enabled
  systemd:
    name: k3s
    daemon_reload: yes
    enabled: yes
  when: master_service

- name: Ensure K3s node service is disabled
  systemd:
    name: k3s-node
    daemon_reload: yes
    enabled: no
  when: not node_service

- name: Ensure K3s node service is enabled
  systemd:
    name: k3s-node
    daemon_reload: yes
    enabled: yes
  when: node_service

- name: Compress the OS image
  community.general.archive:
    path: /opt/os.img
    dest: "/opt/ubuntu-{{ ubuntu_version }}-{{ inventory_hostname }}-{{ rpi_static_ip }}.zip"
    format: zip
  delegate_to: "{{ groups['vm'][0] }}"